name: Deploy to github pages
on:
  push:
    branches:
      - main
jobs:
  build-and-publish-to-github-pages:

    runs-on: ubuntu-latest
    env: 
      PERSONAL_TOKEN: ${{ secrets.PAT_DEPLOY_TO_PAGES }}

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_DEPLOY_TO_PAGES }}
    - uses: actions/setup-node@v3
      with:
        token: ${{ secrets.PAT_DEPLOY_TO_PAGES }}
        node-version: 16
    - name: Publish to Github Pages
      run: |
        npm run build 
        ng deploy --base-href=/festival_planner/