name: Deploy to github pages
on:
  push:
    branches:
      - main
jobs:
  build-and-publish-to-github-pages:

    runs-on: ubuntu-latest
    env: 
      PERSONAL_TOKEN: ${{ secrets.PAT_DEPLOY_TO_PAGES }}

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_DEPLOY_TO_PAGES }}
    - uses: actions/setup-node@v3
      with:
        token: ${{ secrets.PAT_DEPLOY_TO_PAGES }}
        node-version: 16
    - name: Install
      run: |
        npm install
    - name: Build application
      run: |
        npm run build -- --output-path docs --base-href /festival_planner/
        cp docs/index.html docs/404.html

    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.PAT_DEPLOY_TO_PAGES }}
        #publish_dir: dist/festival-planner
        publish_dir: docs
        