name: Deploy to github pages
on:
  push:
    branches:
      - main
jobs:
  build-and-publish-to-github-pages:

    runs-on: ubuntu-latest
    env: 
      PERSONAL_TOKEN: ${{ secrets.PAT_DEPLOY_TO_PAGES }}

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT_DEPLOY_TO_PAGES }}
    - name: Publish to Github Pages
      run: |
        ng deploy --base-href=/festival_planner/